global:
  scrape_interval: 15s

scrape_configs:
  - job_name: gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["api-gateway:9000"]
  - job_name: services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - "identity-service:9000"
          - "asset-service:9000"
          - "maintenance-service:9000"
          - "inventory-service:9000"
          - "notification-service:9000"
          - "organization-service:9000"
